CREATE TABLE CONTACTS(
ID INT GENERATED BY DEFAULT AS IDENTITY, 
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
PHONE VARCHAR(15),
PRIMARY kEY(ID)
)

INSERT
INTO CONTACTS(FIRST_NAME, LAST_NAME, EMAIL, PHONE)
VALUES
('John', 'Doe', 'john.doe@example.com', NULL),
('Lily', 'Bush', 'lily.bush@example.com', '(408-234-2764)');

COMMIT;

SELECT * FROM contacts;
-- null인지 판단할 때 '=' 연산으로 출력되지 않는다!!!
-- null => 아무것도 아닌값 => isnull or is not null 로 판단한다.
-- SELECT * FROM contacts WHERE phone = NULL;
SELECT * FROM contacts WHERE phone IS NULL;
SELECT * FROM contacts WHERE phone IS NOT NULL;


